abstract: Allows your classes to do coercion of parameters
author: Adam Kennedy <adamk@cpan.org>
build_requires: 
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Params-Coerce
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  Params::Util: 0.05
  Scalar::Util: 1.11
  perl: 5.005
version: 0.14
